# This is an alg document
alg is short for ALmost orG, and comes from emacs' org mode.

# Why is this a thing?
Because I'm too stubborn to learn how to use something that already exists instead of reinventing the wheel.

## The # marks a header
That means it defines a section of the document.
Having multiple lines breaks it???
Nevermind, I fixed it.

### The number of # marks the level of the header
The lower levels are contained within the higher ones.

#### The maximum level is 6
It's infinite in org mode, but I want this to be a superset of markdown.

##### I am determined to get to a level 6
I'm not even sure what to write anymore.

###### So here it is
####### Trying to add a level 7 header won't work.

###### And another one because it helps test things
This is all just for testing.

### Something something

#### Something else


### Now we can go back a few levels
I'm running out of things to say.

## Every header can have subheaders
I talked about that already didn't I?

## They can exist in parallel
That's totally obvious.

### You know how a list structure works anyway
I needed something for testing ok?
Give me a break.
Well apparentely this doesn't work.

### Now I'm just making things up because I need tests
Yaaay, random text!
asdf
asdf

### This is probably enough
IS IT THOUGH???

# But adding another level 1 helps with testing
Ok now I'll stop.
For real, now.

## I have to test something
It's about EOF.
So here we go. Another header.
